### ISSUE TITLE
ngx.location.capture('/v1/grbac/functions/tree_parsing', ……)

### ISSUE THREAD

**Issue by jingb** [1046102779/grbac#1]
关于这个location  ngx.location.capture('/v1/grbac/functions/tree_parsing', ……)
是否有权限的逻辑，是lua直接连数据库进行权限校验，还是你后台的go语言去做权限校验
希望可以在README里说明下或者贴下核心代码  谢谢

**Comment by 1046102779** [comment]
是grbac这个web服务做权限校验的。nginx只是做转发。直接用lua作权限校验，是比较好。

**Comment by 1046102779** [comment]
closed.
